FROM golang:1.23.7-alpine3.20
ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=arm64

RUN apk add --no-cache make git bash

WORKDIR /go/src/github.com/stork-oracle/gotrue

# Pulling dependencies
COPY ./Makefile ./go.* ./

# Production dependencies
RUN make deps

# Development dependences
RUN go get github.com/githubnemo/CompileDaemon
RUN go install github.com/githubnemo/CompileDaemon
